### PR TITLE
Improve linux compatability

### PR DESCRIPTION
**Pull request by jumpers775**
In this PR I have significantly improved Linux support. I have only been able to test with steam as that is where I own the game. The methods used to run it may not be compatible with other platforms as I rely on using the games proton prefix from steam to enable DRM. Additionally this requires that [umu-launcher](https://github.com/Open-Wine-Components/umu-launcher) be a dependency and the game must be run once on steam before it works. Failure to meet either of these requirements will not produce a graphical error.

nitroxonlinux

What works:
 - Launching the game with or without multiplayer (if owned on steam)
 - Running server inside or outside the launcher
 - the full launcher
 - game installation detection (steam, env var, config file)
 - compilation

What doesnt work:
 - using built in headerbar only
   - I have switched to using the native headerbar on linux only, let me know if i should revert this 
 - platforms other than steam
   - I do not have these platforms to test, and a different method to enable DRM will likely be required.

### CODE REVIEW

**Comment by jumpers775** [comment]
spent some time working on removing the native window decorations today; It doesnt look good. Avalonia on linux just doesnt disable it, and manually requesting it from X11 doesnt seem to work either. Someday (maybe when avalonia gets wayland support?) it should just start working. In the meantime perhaps it would be best to just disable the custom titlebar on linux?

Additionally, umu-launcher is designed to be bundled with application launchers which use it. What this means is that we should either bundle it or find a different solution. The reason I am using it right now is because running proton outside of steam is really tricky to get right and will change with newer versions of proton, while umu-launcher will always work. Some version of proton is required because it must be run on the steam-built proton prefix if we want DRM to work so we cant use wine. Using proton on steams prefix also has the added benefit of ensuring that singleplayer saves appear when the game is launched through the launcher. This is also why the game must be launched on steam first, otherwise the prefix wont come with steam and thus the DRM wont work.  Given this, umu-launcher should be bundled with nitrox. What is the best way to do this?

**Comment by jumpers775** [comment]
I have updated ProcessEx to support linux and macOS. I dont however have a mac or windows machine to test this on, but it works on linux now and should still work on windows. On mac at worst it should work the same (not at all).

**Review by Measurity — CHANGES_REQUESTED** [review]
Thanks for helping out.

I'm not familiar with umu launcher. But if it needs to be packaged with Nitrox I would prefer to launch the game through Steam as installed by user, and assume the user configured it correctly for use via Proton.

I think more players will use the above method as umu launcher seems somewhat niche. So then I suggest changing the PR to check for umu launcher availability, and if not, fallback to using Steam Proton. 

(I'm currently on Linux and trying make it work with Steam Proton natively.)

**Comment by jumpers775** [comment]
I have made those changes and updated it to use the proton version selected in steam, from steam. This works with all Proton version including GE and other custom versions as long as they can work with steam Linux runtime sniper.

**Comment by jumpers775** [comment]
it appears that this does not compile on windows, I will spin up a VM and investigate

**Comment by jumpers775** [comment]
upon further testing it appears that there is some sort of race condition within the build scripts where something somewhere tries to access NitroxModel-Subnautica.dll while it is still open. I have been able to reproduce this only once, and it does not appear to be a result of this PR. 

Additionally, there appears to be a game corruption bug somewhere that also is not a result of this PR.

**Comment by Measurity** [comment]
Does the race condition also happen when only building the launcher (i.e. not a solution rebuild)?

**Comment by jumpers775** [comment]
I can no longer reproduce it. I was able to get it to error once in a VM and twice on a spare system at work I no longer have access to.

**Comment by jumpers775** [comment]
This PR is now functional on both linux and windows.

**Comment by Schweeeeeeeeeeeeeeee** [comment]
Works 😍

**Comment by PaperTobi** [comment]
Error while starting game in multiplayer mode
System.ArgumentNullException: Value cannot be null. (Parameter 'path1')
   at System.ArgumentNullException.Throw(String paramName)
   at System.IO.Path.Combine(String path1, String path2)
   at NitroxModel.Platforms.Store.Steam.StartGameAsync(String pathToGameExe, Int32 steamAppId, String launchArguments) in NitroxModel/Platforms/Store/Steam.cs:line 310
   at Nitrox.Launcher.ViewModels.LaunchGameViewModel.StartSubnauticaAsync(String[] args) in Nitrox.Launcher/ViewModels/LaunchGameViewModel.cs:line 236
   at Nitrox.Launcher.ViewModels.LaunchGameViewModel.StartMultiplayerAsync(String[] args) in Nitrox.Launcher/ViewModels/LaunchGameViewModel.cs:line 162
   
   Help me please :(

**Comment by jumpers775** [comment]
it seems like proton is probably not installed (it defaults to 9 if no version is selected in steam). i just added some error handling for this, and some graphical indicator should be added but that's above me. if it runs in steam it should run in here.

**Review by PaperTobi — APPROVED** [review]
Now it works. Thank you

**Comment by anewusername** [comment]
Attempting to hit "PLAY" results in an error:
`pressure-vessel-adverb[248493]: E: Failed to execute child process “/redacted/SteamLibrary/steamapps/common/SteamLinuxRuntime_sniper/pressure-vessel/bin/steam-runtime-launcher-interface-0” (No such file or directory)`
The file in question does exist.

From a little digging, I suspect this is related to using multiple steam library paths, or just having my main library path on a different mountpoint from steam itself.

**Review by Schweeeeeeeeeeeeeeee — APPROVED** [review]

**Comment by PeterStrick** [comment]
After having compiled this using `git clean -xdf && dotnet restore && dotnet build -c Release Nitrox.Launcher` I can confirm that the Launcher, Server and Game itself run fine on Windows 11 24H2, Windows 10 22H2, Windows 10 IoT Enterprise LTSC 2021, and the latest Arch Linux Release (Wayland), with further testing happening on NixOS (X11)

The only thing that broke when compiling the Release Build are the `#if RELEASE` block at https://github.com/jumpers775/Nitrox/blob/72b63d0c6518b04038fbd4061be7c0206dd6496b/Nitrox.Launcher/Models/Utils/GameInspect.cs#L60, due to it saying it can't find `ProcessExists`, which can be commented out without Issue or it can be built as Debug instead of Release

Entire Error:

`/root/tmp/Nitrox/Nitrox.Launcher/Models/Utils/GameInspect.cs(61,55): error CS0117: 'ProcessEx' does not contain a definition for 'ProcessExists' [/root/tmp/Nitrox/Nitrox.Launcher/Nitrox.Launcher.csproj]`

**Review by Measurity — APPROVED** [review]

**Pull request merged**
